name: ascii value printing

on:
  push

jobs:
  ascii_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Install the cowsay program
        run: sudo apt-get update && sudo apt-get install cowsay -y
      
      - name: Run cowsay and write to file
        run: cowsay -f dragon "Run for cover, i am a DRAGON.....RAWR" > dragon.txt

      - name: Test file exists and has 'dragon'
        run: grep -i "dragon" dragon.txt

      - name: Read file
        run: cat dragon.txt

      - name: List repo files
        run: ls -lrt
