name: testing job lets see

on:
  push:
    branches:
      - main

jobs:
    build_job1:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: install java
        uses: actions/setup-java@v5
        with:
          java-version: '17'
           distribution: 'temurin'
    
    build_job2:
         needs: build_job1
        build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: build with maven
        run: mvn clean install
